palette:
  top: '#fff'
  bottom: '#fff'
  bg: '#ffffff'
  sidebar: '#ffffff'
  sidebarborders: '#d0d0d0'
  footer: '#fff'
  titleslogan: '#ffffff'
  text: '#3b3b3b'
  link: '#26316c'
logo: 'public://color/bartik-39833908/logo.svg'
stylesheets:
  - 'public://color/bartik-39833908/colors.css'
files:
  - 'public://color/bartik-39833908/logo.svg'
  - 'public://color/bartik-39833908/colors.css'
