api:
  domain: independence-visitor-center-corporation.myshopify.com
  key: 85db94b47d375f4aed11cb2aeed9a483
  password: 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
  secret: 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
_core:
  default_config_hash: VbSmiDt1Hmlwjazl5292qqEQMD5JOrfBZ0se5nUD-tY
