domain: independence-visitor-center-corporation.myshopify.com
api_key: 85db94b47d375f4aed11cb2aeed9a483
password: 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
shared_secret: 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
_core:
  default_config_hash: udKj72CZ_w3BDHIhs60liLXO-9YBbxRwn7PVsFt9x7M
